name: kedro
title: Kedro
summary: Python framework for data science pipelines
description: |
  Kedro is a toolbox for production-ready data science.
  It uses software engineering best practices to help you
  create data engineering and data science pipelines that are
  reproducible, maintainable, and modular.
base: core24
adopt-info: kedro

grade: devel
confinement: strict

apps:
  kedro:
    command: bin/kedro
    plugs:
      - network
      - home
      - personal-files

parts:
  kedro:
    plugin: uv
    source: https://github.com/kedro-org/kedro.git
    source-branch: &VERSION '0.19.13'
    source-depth: 1
    build-snaps:
      - astral-uv
    build-environment:
      - UV_FROZEN: "false"  # There is no `uv.lock`, it has to be generated
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)

platforms:
  amd64:
