name: kedro
title: Kedro
summary: Python framework for data science pipelines
description: |
  Kedro is a toolbox for production-ready data science.
  It uses software engineering best practices to help you
  create data engineering and data science pipelines that are
  reproducible, maintainable, and modular.
base: core24
adopt-info: kedro

grade: devel
confinement: strict

apps:
  kedro:
    command: bin/kedro
    plugs:
      - network
      - home
      - kedro-config

parts:
  kedro:
    plugin: uv
    source: https://github.com/kedro-org/kedro.git
    source-branch: &VERSION '0.19.13'
    source-depth: 1
    build-snaps:
      - astral-uv
    build-environment:
      - UV_FROZEN: "false"  # There is no `uv.lock`, it has to be generated
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
    stage-packages:
      - git  # FIXME: git is not capable of cloning https repos: 'remote-https' is not a git command
      # openssl and libssl3t64 are being filtered out "skipping filtered manifest packages", why?
      # Should I include them in build-packages?

plugs:
  kedro-config:
    interface: personal-files
    write:
      - $HOME/.config/kedro

platforms:
  amd64:
